* Douanes
Projet de script python pour la consultation de la base de données du tarif douanier.

* État des lieux
La direction générale des douanes met à disposition du public une base de données du tarif douanier à l'adresse suivante.

http://www.douane.gov.dz/applications/tarif/

La navigation dans les sections et sous-sections de la base s'appuie sur un fichier Javascript [[init1.js]]

* Objectifs

Le programme devrait faciliter l'accès à cette base en en créant une copie locale sous format text.
* Étapes
** Home page
Le script interroge la page d'accueil et renvoie le [[sortie_print_home_page.html][contenu]].

Les numéros de section et leurs intitulés sont identifiés comme suit :
#+BEGIN_SRC html
<div id="codenum">
<div id="descr">
#+END_SRC
** TODO Parser la réponse
Le script devra devra dans un premier temps lister les codes et les descriptions.
Par la suite utiliser les codes pour générer une requête plus en profondeur vers les sous-sections.
* Codes à garder sous la main
#+BEGIN_SRC python
import urllib # on en aura besoin quand il faudra envoyer des requêtes en GET
from bs4 import BeautifulSoup # on verra l'usage dans la section 2 du code
# user_agent = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)' # au cas où ça s'impose
# headers = { 'User-Agent' : user_agent }

###### Section 2
#soup = BeautifulSoup(home_page, 'html.parser')
# edit = soup.prettify()

# fo.close()
# soup.title
#+END_SRC
