* Douanes
Projet de script python pour la consultation de la base de données du tarif douanier.

* État des lieux
La direction générale des douanes met à disposition du public une base de données du tarif douanier à l'adresse suivante.

http://www.douane.gov.dz/applications/tarif/

La navigation dans les sections et sous-sections de la base s'appuie sur un fichier Javascript [[init1.js]]

* Objectifs
Le programme devrait faciliter l'accès à cette base en en créant une copie locale sous format text.
* Étapes
** DONE Tirer la home page
   CLOSED: [2016-01-09 sam. 10:36]
Le script [[douanes.py]] interroge la page d'accueil et enregistre le [[s_p_h_p_BeautifulSoup.html][contenu]] en local.

Les numéros de section et leurs intitulés sont identifiés comme suit :
#+BEGIN_SRC html
<div id="codenum">
<div id="descr">
#+END_SRC
** DONE Parser la réponse
   CLOSED: [2016-01-09 sam. 10:29]
Le script [[proclocal.py][prolocal.py]] parse le fichier obtenu à l'étape précédente pour extraire [[section1.txt][les codes et les descriptions correspondantes]].
** TODO Explorer le 2e niveau
Utiliser les codes pour générer une requête plus en profondeur vers les sous-sections.
** TODO Observations
C'est à ce niveau que la programmation orientée objet commence à prendre son sens.
Au lieu d'enregistrer les résultats à chaque étape des fonctions ou des modules pourrait se renvoyer les résultats internes sous formes de données structurées.
En l'état [[proclocal.py][prolocal.py]] enregistre le résultat (code et description) dans une variable de type dictionnaire.
#+BEGIN_SRC python
dict_sections[code] = spec
#+END_SRC

* Codes à garder sous la main
#+BEGIN_SRC python
import urllib # on en aura besoin quand il faudra envoyer des requêtes en GET
from bs4 import BeautifulSoup # on verra l'usage dans la section 2 du code
# user_agent = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)' # au cas où ça s'impose
# headers = { 'User-Agent' : user_agent }
###### Section 2
# fo.close()
# soup.title
#+END_SRC
